function [globalPlanes, bufferComposedPlanes]=mergeIntoGlobalPlanes_vcuboids(localPlanes,...
            globalPlanesPrevious,tao_merg,theta_merg, lengthBoundsTop,...
            lengthBoundsP,bufferComposedPlanes, planeFilteringParameters, planeModelParameters, gridStep, compensateFactor)
%MERGEINTOGLOBALPLANES_VCUBOID performs a merge btwn planes with the same
%type
%   Detailed explanation goes here
% [globalPlanesPrevious.xz, xyp_gpp, zyp_gpp]=extractTypes_vcuboids(globalPlanesPrevious);
% [localPlanes.xzIndex, localPlanes.xyIndex, localPlanes.zyIndex]=extractTypes_vcuboids(localPlanes.values);

[globalPlanes_xz, bufferComposedPlanes_xz]=mergeIntoGlobalPlanes_v3(localPlanes.values(localPlanes.xzIndex),...
            globalPlanesPrevious.values(globalPlanesPrevious.xzIndex),...
            tao_merg,theta_merg, lengthBoundsTop,...
            lengthBoundsP,bufferComposedPlanes.xz, planeFilteringParameters,...
            planeModelParameters, gridStep, compensateFactor, localPlanes.cameraPose);

[globalPlanes_xy, bufferComposedPlanes_xy]=mergeIntoGlobalPlanes_v3(localPlanes.values(localPlanes.xyIndex),...
            globalPlanesPrevious.values(globalPlanesPrevious.xyIndex),...
            tao_merg,theta_merg, lengthBoundsTop,...
            lengthBoundsP,bufferComposedPlanes.xy, planeFilteringParameters,...
            planeModelParameters, gridStep, compensateFactor, localPlanes.cameraPose);

[globalPlanes_zy, bufferComposedPlanes_zy]=mergeIntoGlobalPlanes_v3(localPlanes.values(localPlanes.zyIndex),...
            globalPlanesPrevious.values(globalPlanesPrevious.zyIndex),...
            tao_merg,theta_merg, lengthBoundsTop,...
            lengthBoundsP,bufferComposedPlanes.zy, planeFilteringParameters,...
            planeModelParameters, gridStep, compensateFactor, localPlanes.cameraPose);

globalPlanes.values=[globalPlanes_xz, globalPlanes_xy,globalPlanes_zy];
[xzIndex, xyIndex, zyIndex]=extractTypes_vcuboids(globalPlanes.values);
globalPlanes.xzIndex=xzIndex;
globalPlanes.xyIndex=xyIndex;
globalPlanes.zyIndex=zyIndex;

% find duplicateID in composed planes and update
bufferComposedPlanes.xz=bufferComposedPlanes_xz;
bufferComposedPlanes.xy=bufferComposedPlanes_xy;
bufferComposedPlanes.zy=bufferComposedPlanes_zy;

end

